version: '3'
services:
  php:
    build: docker
    expose:
      - '9000'
    volumes:
      - ./:/var/www/qpony
  nginx:
    image: nginx:1.13.8
    ports:
      - 80:80
    volumes:
      - ./:/var/www/qpony
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php